/// <summary>
/// Holds all pre-written narration strings for the VR biology tutor.
///
/// These are the fixed lines the AI agent speaks automatically at phase
/// transitions and key moments. They are not generated by OpenAI — they
/// are spoken directly through TTS via AITutor.SpeakNarration().
///
/// This is the single file to edit for all narration copy.
/// No Unity dependencies, no logic — strings only.
/// </summary>
public static class NarrationLines
{
    // ── Cycle 1 phase introductions ───────────────────────────────────────────

    public static readonly string Intro =
        "Welcome! I'm Carla, your personal biology tutor! Feel free to ask me any question about biology."  + 
        "Infront of you, there is a hand with a wound on it. It looks painful!" + 
        "You're here to help heal the wound by guiding a cell through mitosis — " +
        "the process cells use to divide and create identical copies of themselves for growth and repair. " +
        "To get started, touch and hold the wound on the hand for about 3 seconds to shrink down and enter the cell!";
        // set timer in each phase for agent to say ask me questions if you are stuck

    public static readonly string Interphase =
        "You've entered the cell! This is Interphase — the preparation stage where the cell gathers energy " +
        "before it can divide. Just like how humans eat food to get energy, the cell needs nutrients too! " +
        "Grab the three green nutrient capsules — Protein, Magnesium, and Vitamin C — and place them into " +
        "the mitochondria to charge up the cell's ATP energy. Watch the green ATP bar fill up as you go!";
        // HAVE THE AI AGENT DO A POINT GESUTRE WHEN TAlkING ABOUT THE ATP BAR
        // also make the atp bar and hp bar have segments that light up as they fill up

    public static readonly string InterphasePart2 =
        "The cell's energy is charged up! Now you need to duplicate the centriole — find the yellow " +
        "barrel-shaped centriole and grab it to create a copy. The centrioles will move to opposite sides " +
        "of the cell and organize the spindle fibers that will move the chromosomes during division!";
        // also mention that you should grab and move the centriole

    public static readonly string Prophase =
        "Now we're in Prophase — where the cell's DNA condenses into an X-shape and the spindle " +
        "fibers begin to form. Find the red stringy DNA and grab it, then hold it steady for about " +
        "6 seconds so it condenses into a tightly packed X-shaped chromosome. This X shape is actually " +
        "two identical copies of the DNA joined together, ready to be separated into the new cells!";

    public static readonly string Metaphase =
        "This is Metaphase, where all the chromosomes line up along the center of the cell so they can be " +
        "evenly divided. Grab the red X-shaped chromosome and move it to the sparkly area in the middle " +
        "to align it with the other chromosomes. Each new cell must receive exactly one complete copy of every chromosome!";

    public static readonly string Anaphase =
        "Now we're in Anaphase — the stage where the chromosomes are pulled apart! Grab each side of the " +
        "red X-shaped chromosome and pull the two halves apart, separating the sister chromatids. Then place " +
        "one chromatid on each side of the cell. This is when the genetic material is separated so each daughter cell can get one complete copy";

    // ── Telophase — spoken every cycle ───────────────────────────────────────

    public static readonly string[] Telophase =
    {
        // Cycle 1 (healingCycleCount == 0)
        "Great work! You've completed the first round of cell division. " +
        "The wound isn't fully healed yet though — in real tissue, many cells must " +
        "divide multiple times to fully repair the damage. " +
        "Also, notice the red bar at the top — that's your healing progress. " +
        "Each time the cell successfully divides, the wound heals a little more. " +
        "Touch the wound again to continue!",
        // add that to they need to look at the 2 cells splitting
        // explain that from now on that she wont start conversation, so ask me question if you want

        // Cycle 2 (healingCycleCount == 1)
        "Excellent! Two rounds of cell division complete. The wound is healing nicely, " +
        "but we need one more cycle to fully restore the tissue. Let's finish this!",

        // Cycle 3 (healingCycleCount == 2)
        "Congratulations! You've completed all three rounds of mitosis and fully healed the wound. " +
        "You've just seen how cells work together to repair tissue. " +
        "Touch the healed hand to complete the simulation."
    };

    /// <summary>
    /// Returns the correct Telophase line for the current healing cycle,
    /// or an empty string if the cycle index is out of range.
    /// </summary>
    public static string GetTelophase(int healingCycleCount)
    {
        if (healingCycleCount >= 0 && healingCycleCount < Telophase.Length)
            return Telophase[healingCycleCount];
        return "";
    }
}